version: '3.8'

services:
  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 10s
      timeout: 5s
      retries: 5

  express-service:
    build:
      context: ./express-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - go-service
    restart: unless-stopped
    environment:
      - GRPC_SERVER=go-service:50051

networks:
  app-network:
    driver: bridge